"""Pydantic mirrors of the backend's zod LLM-output schemas (llm/schemas/*.ts).

These are the canonical shapes every LLM-proposed output is forced into via LangChain's
with_structured_output(), regardless of which provider in LLM_MODELS answers — kept
field-for-field identical to strategy-params.schema.ts / live-decision.schema.ts so a
strategy generated by the worker is indistinguishable from one generated by the backend.
"""
from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field


class IndicatorConfig(BaseModel):
    # The knobs the backtest AND live engines actually trade on — every one is really used
    # (unlike the old phantom RSI). trendEmaPeriod is a REAL, optional trend-regime filter wired
    # into the simulate/live/replay paths of both engines (parity-verified by
    # tools/parity_evaluator.py); when set, LONG entries are only taken while price is above it.
    emaFastPeriod: int = Field(..., ge=2, le=100, description="Fast EMA period in candles")
    emaSlowPeriod: int = Field(..., ge=5, le=300, description="Slow EMA period in candles")
    trendEmaPeriod: Optional[int] = Field(
        None, ge=20, le=400,
        description="Long-term trend EMA period; LONG entries are only taken when price is above "
        "this EMA (trend-regime filter that cuts whipsaws in ranging/down markets). Should be "
        "longer than emaSlowPeriod. Omit to disable the filter.",
    )
    stopLossPct: float = Field(..., ge=0.1, le=20, description="Stop-loss as a percent, e.g. 1.5 for 1.5%")
    takeProfitPct: float = Field(..., ge=0.1, le=50, description="Take-profit as a percent, e.g. 3.5 for 3.5%")


class StrategyParams(BaseModel):
    """Canonical shape every LLM-proposed strategy must be forced into (mirrors
    StrategyParamsSchema)."""

    strategyName: str = Field(..., description="Short human-readable name for this strategy variant")
    indicatorConfig: IndicatorConfig
    reasoning: str = Field(..., description="Brief rationale for these parameter choices")


class StrategyGen(BaseModel):
    """DSL rule-tree generation output (mirrors StrategyGenSchema). entry/exit/risk are permissive
    dicts on purpose — the REAL structural check is validate_ir() in the caller, and a loose schema
    lets every provider's JSON coerce cleanly (matches the backend's z.any() fields)."""

    strategyName: str = Field(..., description="Short human-readable name for this strategy")
    reasoning: str = Field("", description="Brief rationale tied to the lessons and the market")
    direction: Optional[Literal["long", "short"]] = Field(
        None, description="'long' (default) or 'short' (futures markets only)")
    entry: dict = Field(..., description="Condition tree that, when true and flat, opens the position")
    exit: dict = Field(..., description="Condition tree that closes the open position (risk block also applies)")
    risk: dict = Field(..., description="{stopLossPct, takeProfitPct, and optionally trailingStopPct, maxHoldBars}")


class GenerationPlan(BaseModel):
    """Meta-planner output (mirrors GenerationPlanSchema). Proposed gate thresholds are a REQUEST —
    the caller clamps every one to a hard floor before use."""

    interval: Literal["1h", "2h", "4h", "6h", "12h", "1d"] = Field(..., description="Timeframe to generate & backtest on")
    candleLimit: int = Field(..., ge=1000, le=20000, description="How many bars of `interval` to backtest over")
    minSharpe: float = Field(..., ge=0, le=3, description="Proposed OOS Sharpe bar (clamped to >=0.5)")
    minProfitFactor: float = Field(..., ge=1, le=3, description="Proposed profit-factor bar (clamped to >=1.2)")
    maxDrawdownPct: float = Field(..., ge=5, le=50, description="Proposed max-drawdown ceiling % (clamped to <=25)")
    minTradeCount: int = Field(..., ge=5, le=300, description="Proposed minimum OOS trades (clamped to >=5)")
    signalEmphasis: str = Field(..., description="Concrete guidance for the generator given the lessons")
    reasoning: str = Field(..., description="Brief rationale tying the plan to the lessons")


class LiveDecision(BaseModel):
    """Mode B live-decision output (mirrors LiveDecisionSchema)."""

    action: Literal["BUY", "SELL", "HOLD"] = Field(..., description="The trading action to take right now")
    reasoning: str = Field(..., description="Brief rationale for this decision")


class ExitTightenDecision(BaseModel):
    """Phase 2 hybrid AI exit overlay output (mirrors ExitTightenDecisionSchema). The AI may only
    EXIT early to protect profit or HOLD to keep riding — it can never re-open or block a rules exit."""

    action: Literal["EXIT", "HOLD"] = Field(
        ..., description="EXIT to book the open position now (the move looks exhausted), or HOLD to keep riding the trend")
    reasoning: str = Field(..., description="Brief rationale for this decision")
