"""Pydantic mirrors of the backend's zod LLM-output schemas (llm/schemas/*.ts).

These are the canonical shapes every LLM-proposed output is forced into via LangChain's
with_structured_output(), regardless of which provider in LLM_MODELS answers — kept
field-for-field identical to strategy-params.schema.ts / live-decision.schema.ts so a
strategy generated by the worker is indistinguishable from one generated by the backend.
"""
from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field


class IndicatorConfig(BaseModel):
    # The knobs the backtest AND live engines actually trade on — every one is really used
    # (unlike the old phantom RSI). trendEmaPeriod is a REAL, optional trend-regime filter wired
    # into the simulate/live/replay paths of both engines (parity-verified by
    # tools/parity_evaluator.py); when set, LONG entries are only taken while price is above it.
    emaFastPeriod: int = Field(..., ge=2, le=100, description="Fast EMA period in candles")
    emaSlowPeriod: int = Field(..., ge=5, le=300, description="Slow EMA period in candles")
    trendEmaPeriod: Optional[int] = Field(
        None, ge=20, le=400,
        description="Long-term trend EMA period; LONG entries are only taken when price is above "
        "this EMA (trend-regime filter that cuts whipsaws in ranging/down markets). Should be "
        "longer than emaSlowPeriod. Omit to disable the filter.",
    )
    stopLossPct: float = Field(..., ge=0.1, le=20, description="Stop-loss as a percent, e.g. 1.5 for 1.5%")
    takeProfitPct: float = Field(..., ge=0.1, le=50, description="Take-profit as a percent, e.g. 3.5 for 3.5%")


class StrategyParams(BaseModel):
    """Canonical shape every LLM-proposed strategy must be forced into (mirrors
    StrategyParamsSchema)."""

    strategyName: str = Field(..., description="Short human-readable name for this strategy variant")
    indicatorConfig: IndicatorConfig
    reasoning: str = Field(..., description="Brief rationale for these parameter choices")


class StrategyGen(BaseModel):
    """DSL rule-tree generation output (mirrors StrategyGenSchema). entry/exit/risk are permissive
    dicts on purpose — the REAL structural check is validate_ir() in the caller, and a loose schema
    lets every provider's JSON coerce cleanly (matches the backend's z.any() fields)."""

    strategyName: str = Field(..., description="Short human-readable name for this strategy")
    reasoning: str = Field("", description="Brief rationale tied to the lessons and the market")
    # REQUIRED, never optional: an omitted direction silently defaulted to long, so a short-shaped
    # rule tree ("enter when RSI is OVERBOUGHT in a downtrend") was executed and backtested as a
    # LONG — i.e. exactly inverted. Forcing the model to state it makes that impossible.
    direction: Literal["long", "short", "both"] = Field(
        ..., description="'long' (buy to open, sell to close), 'short' (sell to open, buy to cover — "
                         "futures only), or 'both' (trade BOTH sides — futures only; requires "
                         "shortEntry/shortExit). MUST match the rule tree: an entry on an "
                         "OVERBOUGHT/downtrend condition is a SHORT; oversold/uptrend is a LONG.")
    entry: dict = Field(..., description="Condition tree that, when true and flat, opens the position "
                                         "(the LONG side when direction is 'both')")
    exit: dict = Field(..., description="Condition tree that closes the open position (risk block also applies)")
    shortEntry: Optional[dict] = Field(
        None, description="REQUIRED when direction is 'both': the SHORT entry, mirroring `entry` "
                          "(same indicators/periods, opposite thresholds and trend filter)")
    shortExit: Optional[dict] = Field(
        None, description="REQUIRED when direction is 'both': the SHORT exit, mirroring `exit`")
    risk: dict = Field(..., description="{stopLossPct, takeProfitPct, and optionally trailingStopPct, maxHoldBars}")


class StrategyTemplate(BaseModel):
    """Two-stage generation, Stage 1 output: a strategy SHAPE. Same rule tree as StrategyGen, but
    tunable numbers are {"$param": "name"} markers and `search` lists candidate values per name;
    the optimizer (Stage 2) grid-searches them on the data. entry/exit/risk stay permissive dicts."""

    strategyName: str = Field(..., description="Short human-readable name")
    reasoning: str = Field("", description="Why this shape, tied to lessons/market")
    # Required for the same reason as StrategyGen.direction — see the note there.
    direction: Literal["long", "short", "both"] = Field(
        ..., description="'long' (buy to open), 'short' (sell to open — futures only), or 'both' "
                         "(trade BOTH sides — futures only; requires shortEntry/shortExit). MUST "
                         "match the rule tree: an OVERBOUGHT/downtrend entry is a SHORT, "
                         "oversold/uptrend is a LONG.")
    search: dict = Field(..., description='Param name -> list of candidate values, e.g. {"oversold":[28,32,35]}')
    entry: dict = Field(..., description="Entry condition tree with {\"$param\":\"name\"} leaves "
                                         "(the LONG side when direction is 'both')")
    exit: dict = Field(..., description="Exit condition tree with {\"$param\":\"name\"} leaves")
    shortEntry: Optional[dict] = Field(
        None, description="REQUIRED when direction is 'both': SHORT entry mirroring `entry`. REUSE "
                          "the same {\"$param\":\"name\"} period markers so both sides share periods.")
    shortExit: Optional[dict] = Field(
        None, description="REQUIRED when direction is 'both': SHORT exit mirroring `exit`")
    risk: dict = Field(..., description="Risk object with {\"$param\":\"name\"} leaves")


class GenerationPlan(BaseModel):
    """Meta-planner output (mirrors GenerationPlanSchema). Proposed gate thresholds are a REQUEST —
    the caller clamps every one to a hard floor before use."""

    interval: Literal["1h", "2h", "4h", "6h", "12h", "1d"] = Field(..., description="Timeframe to generate & backtest on")
    candleLimit: int = Field(..., ge=1000, le=20000, description="How many bars of `interval` to backtest over")
    minSharpe: float = Field(..., ge=0, le=3, description="Proposed OOS Sharpe bar (clamped to >=0.5)")
    minProfitFactor: float = Field(..., ge=1, le=3, description="Proposed profit-factor bar (clamped to >=1.2)")
    maxDrawdownPct: float = Field(..., ge=5, le=50, description="Proposed max-drawdown ceiling % (clamped to <=25)")
    minTradeCount: int = Field(..., ge=5, le=300, description="Proposed minimum OOS trades (clamped to >=5)")
    signalEmphasis: str = Field(..., description="Concrete guidance for the generator given the lessons")
    # Structured, so the generator can ENFORCE the plan rather than hoping the next model reads the
    # emphasis prose. Without this the planner asked for BOTH and the generator quietly returned a
    # one-sided strategy, which was then promoted.
    preferredDirection: Literal["long", "short", "both"] = Field(
        ..., description="Which direction the generated strategy MUST take: 'long', 'short', or "
                         "'both' (two-sided, futures only). Must agree with signalEmphasis.")
    reasoning: str = Field(..., description="Brief rationale tying the plan to the lessons")


class LiveDecision(BaseModel):
    """Mode B live-decision output (mirrors LiveDecisionSchema)."""

    action: Literal["BUY", "SELL", "HOLD"] = Field(..., description="The trading action to take right now")
    reasoning: str = Field(..., description="Brief rationale for this decision")


class ExitTightenDecision(BaseModel):
    """Phase 2 hybrid AI exit overlay output (mirrors ExitTightenDecisionSchema). The AI may only
    EXIT early to protect profit or HOLD to keep riding — it can never re-open or block a rules exit."""

    action: Literal["EXIT", "HOLD"] = Field(
        ..., description="EXIT to book the open position now (the move looks exhausted), or HOLD to keep riding the trend")
    reasoning: str = Field(..., description="Brief rationale for this decision")
