"""Pydantic mirrors of the backend's zod LLM-output schemas (llm/schemas/*.ts).

These are the canonical shapes every LLM-proposed output is forced into via LangChain's
with_structured_output(), regardless of which provider in LLM_MODELS answers — kept
field-for-field identical to strategy-params.schema.ts / live-decision.schema.ts so a
strategy generated by the worker is indistinguishable from one generated by the backend.
"""
from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field


class IndicatorConfig(BaseModel):
    # The knobs the backtest AND live engines actually trade on — every one is really used
    # (unlike the old phantom RSI). trendEmaPeriod is a REAL, optional trend-regime filter wired
    # into the simulate/live/replay paths of both engines (parity-verified by
    # tools/parity_evaluator.py); when set, LONG entries are only taken while price is above it.
    emaFastPeriod: int = Field(..., ge=2, le=100, description="Fast EMA period in candles")
    emaSlowPeriod: int = Field(..., ge=5, le=300, description="Slow EMA period in candles")
    trendEmaPeriod: Optional[int] = Field(
        None, ge=20, le=400,
        description="Long-term trend EMA period; LONG entries are only taken when price is above "
        "this EMA (trend-regime filter that cuts whipsaws in ranging/down markets). Should be "
        "longer than emaSlowPeriod. Omit to disable the filter.",
    )
    stopLossPct: float = Field(..., ge=0.1, le=20, description="Stop-loss as a percent, e.g. 1.5 for 1.5%")
    takeProfitPct: float = Field(..., ge=0.1, le=50, description="Take-profit as a percent, e.g. 3.5 for 3.5%")


class StrategyParams(BaseModel):
    """Canonical shape every LLM-proposed strategy must be forced into (mirrors
    StrategyParamsSchema)."""

    strategyName: str = Field(..., description="Short human-readable name for this strategy variant")
    indicatorConfig: IndicatorConfig
    reasoning: str = Field(..., description="Brief rationale for these parameter choices")


class LiveDecision(BaseModel):
    """Mode B live-decision output (mirrors LiveDecisionSchema)."""

    action: Literal["BUY", "SELL", "HOLD"] = Field(..., description="The trading action to take right now")
    reasoning: str = Field(..., description="Brief rationale for this decision")


class ExitTightenDecision(BaseModel):
    """Phase 2 hybrid AI exit overlay output (mirrors ExitTightenDecisionSchema). The AI may only
    EXIT early to protect profit or HOLD to keep riding — it can never re-open or block a rules exit."""

    action: Literal["EXIT", "HOLD"] = Field(
        ..., description="EXIT to book the open position now (the move looks exhausted), or HOLD to keep riding the trend")
    reasoning: str = Field(..., description="Brief rationale for this decision")
